### ISSUE TITLE
`css/cloudogu-black.css` not found

### ISSUE THREAD

**Issue by lhaze** [cloudogu/reveal.js-docker#7]
Error: when using `THEME_CSS=css/cloudogu-black.css` envvar to adjust styling, got:
`"GET /dist/theme/css/cloudogu-black.css HTTP/1.1" 404 555 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36" "-"`

### Reproduction steps:
1. setup `docker-compose.yaml`
```
version: "3.9"
services:
  web:
    image: "cloudogu/reveal.js"
    ports:
      - "8080:8080"
    environment:
        THEME_CSS: css/cloudogu-black.css
```
2. `docker-compose up`

### Probable reason:
`README.md` states, that styling can be applied using `THEME_CSS=css/cloudogu-black.css`

> Optional Env vars:
> ...
> - THEME_CSS
>   - css/cloudogu.css
>   - css/cloudogu-black.css
>   - reveal.js themes

but the CSS files are just in the `/dist/theme` directory, and there's no `css/` subdirectory in it.

Should the description in the `README.md` be adjusted accordingly?
